# Generated by Django 5.2.4 on 2025-07-04 03:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokensolicitacao',
            name='email_cliente',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='tokensolicitacao',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.fornecedor'),
        ),
    ]
